version: '3.1'
services:
  openWebUI:
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    ports:
      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - 'OLLAMA_BASE_URL=http://192.168.1.62:11434/'
    volumes:
      - open-webui-local:/app/backend/data

volumes:
  open-webui-local:
    external: true